import { PrismaClient } from '@prisma/client';
import { config } from 'dotenv';
import { resolve } from 'path';

// Load environment variables
config({ path: resolve(process.cwd(), '.env.local') });

const prisma = new PrismaClient();

// CSV data parsed into array
const plantData = [
  {
    genus: 'Epipremnum',
    species: 'aureum',
    commonName: 'Pothos (Devil\'s Ivy)',
    cycle: 'perennial',
    wateringFrequency: 2,
    nativeRegion: 'Southeast Asia',
    tradeStatus: 0,
    idealTemp: '65-85°F (18-29°C)',
    sunlight: 2,
    description: 'Trailing vine with glossy, heart-shaped green leaves often variegated with yellow or white.',
    idealConditions: 'Tropical/subtropical understory; well-draining potting mix; indoor bright indirect light.',
    careTips: 'Keep in bright, indirect light; water occasionally — allow the top 1–2 inches of soil to dry between waterings. Tolerates low light and neglect; avoid overwatering which causes root rot. Common mistakes: constant wet soil and direct hot sun causing leaf scorch.',
    isEndangered: false,
    isEdible: false,
    isPoisonous: true,
    uniqueFacts: 'Very tolerant of low light and easy to propagate from cuttings.',
    imageURL: '0'
  },
  {
    genus: 'Chlorophytum',
    species: 'comosum',
    commonName: 'Spider Plant',
    cycle: 'perennial',
    wateringFrequency: 3,
    nativeRegion: 'Tropical and Southern Africa',
    tradeStatus: 0,
    idealTemp: '60-75°F (16-24°C)',
    sunlight: 3,
    description: 'Arching, grass-like leaves often variegated; produces long stems with plantlets (\'spiders\').',
    idealConditions: 'Bright indirect light; well-draining soil; moderate humidity; adaptable indoors.',
    careTips: 'Water weekly or when the top inch of soil is dry. Thrives in bright, indirect light but tolerates lower light. Common mistakes: overwatering leading to root rot and placing in harsh direct sun.',
    isEndangered: false,
    isEdible: false,
    isPoisonous: false,
    uniqueFacts: 'Produces baby plantlets on long stolons that are easy to root.',
    imageURL: '0'
  },
  {
    genus: 'Zamioculcas',
    species: 'zamiifolia',
    commonName: 'ZZ Plant',
    cycle: 'perennial',
    wateringFrequency: 1,
    nativeRegion: 'Eastern Africa',
    tradeStatus: 0,
    idealTemp: '60-85°F (16-29°C)',
    sunlight: 1,
    description: 'Glossy, dark green pinnate leaves on thick, succulent-like stems; very tolerant of neglect.',
    idealConditions: 'Well-draining soil; bright indirect to low light; arid-subtropical conditions.',
    careTips: 'Water rarely — about every 2–6 weeks depending on light. Extremely drought-tolerant; avoid waterlogged soil. Common mistakes: overwatering and poor drainage.',
    isEndangered: false,
    isEdible: false,
    isPoisonous: true,
    uniqueFacts: 'Stores water in thick rhizomes, making it extremely drought-tolerant.',
    imageURL: '0'
  },
  {
    genus: 'Monstera',
    species: 'deliciosa',
    commonName: 'Monstera Deliciosa (Swiss Cheese Plant)',
    cycle: 'perennial',
    wateringFrequency: 3,
    nativeRegion: 'Central America',
    tradeStatus: 0,
    idealTemp: '65-85°F (18-29°C)',
    sunlight: 3,
    description: 'Large, leathery leaves that develop natural splits and holes (fenestrations) with maturity.',
    idealConditions: 'Tropical forest understory; bright, indirect light; rich, well-draining soil; humid.',
    careTips: 'Water weekly allowing the top 1–2 inches of soil to dry. Prefers bright indirect light and humidity; avoid direct harsh sun. Common mistakes: overwatering and low humidity causing brown edges.',
    isEndangered: false,
    isEdible: false,
    isPoisonous: true,
    uniqueFacts: 'Fenestrations may help reduce wind resistance and let light reach lower leaves.',
    imageURL: '0'
  },
  {
    genus: 'Spathiphyllum',
    species: 'wallisii',
    commonName: 'Peace Lily',
    cycle: 'perennial',
    wateringFrequency: 4,
    nativeRegion: 'Tropical Americas and Southeast Asia',
    tradeStatus: 0,
    idealTemp: '65-80°F (18-27°C)',
    sunlight: 2,
    description: 'Glossy lance-shaped leaves and white hood-like flowers (spathes) rising above foliage.',
    idealConditions: 'Humid tropical understory; rich, moist, well-draining soil; bright indirect light.',
    careTips: 'Keep soil consistently moist but not waterlogged. Enjoys higher humidity and bright indirect light; wilting indicates need for water. Common mistakes: allowing soil to dry out completely and exposing to direct sun.',
    isEndangered: false,
    isEdible: false,
    isPoisonous: true,
    uniqueFacts: 'Commonly cited in indoor air quality studies for pollutant removal.',
    imageURL: '0'
  },
  {
    genus: 'Ficus',
    species: 'lyrata',
    commonName: 'Fiddle Leaf Fig',
    cycle: 'perennial',
    wateringFrequency: 3,
    nativeRegion: 'Tropical Western Africa',
    tradeStatus: 0,
    idealTemp: '60-75°F (16-24°C)',
    sunlight: 4,
    description: 'Upright tree with large, violin-shaped glossy leaves that can become quite large.',
    idealConditions: 'Warm, bright indoor spots with filtered light; well-draining soil; moderate humidity.',
    careTips: 'Water moderately — allow topsoil to dry slightly between waterings. Needs bright, consistent light and stable environment; avoid drafts and frequent moves. Common mistakes: overwatering and inconsistent light causing leaf drop.',
    isEndangered: false,
    isEdible: false,
    isPoisonous: true,
    uniqueFacts: 'Mature leaves can become very large and dramatic, prized in interior design.',
    imageURL: '0'
  },
  {
    genus: 'Ficus',
    species: 'elastica',
    commonName: 'Rubber Tree',
    cycle: 'perennial',
    wateringFrequency: 3,
    nativeRegion: 'South and Southeast Asia',
    tradeStatus: 0,
    idealTemp: '60-85°F (16-29°C)',
    sunlight: 3,
    description: 'Large, glossy, leathery oval leaves on a tree-like form; some cultivars are variegated.',
    idealConditions: 'Tropical/subtropical; bright indirect light; rich, well-draining soil.',
    careTips: 'Water regularly but allow slight drying between waterings. Prefers bright indirect light; can tolerate lower light. Common mistakes: overwatering and cold drafts causing leaf drop.',
    isEndangered: false,
    isEdible: false,
    isPoisonous: true,
    uniqueFacts: 'Produces latex historically used for rubber production.',
    imageURL: '0'
  },
  {
    genus: 'Crassula',
    species: 'ovata',
    commonName: 'Jade Plant',
    cycle: 'perennial',
    wateringFrequency: 1,
    nativeRegion: 'South Africa and Mozambique',
    tradeStatus: 0,
    idealTemp: '65-75°F (18-24°C)',
    sunlight: 4,
    description: 'Succulent with thick woody stems and fleshy oval leaves often with red edges in sun.',
    idealConditions: 'Arid to semi-arid; well-draining, gritty soil; bright light to full sun.',
    careTips: 'Water sparingly — allow soil to dry almost completely between waterings. Prefers bright light; avoid frequent watering and poor drainage. Common mistakes: overwatering leading to root rot.',
    isEndangered: false,
    isEdible: false,
    isPoisonous: true,
    uniqueFacts: 'Commonly associated with good luck in some cultures; long-lived as a houseplant.',
    imageURL: '0'
  },
  {
    genus: 'Aloe',
    species: 'barbadensis miller',
    commonName: 'Aloe Vera',
    cycle: 'perennial',
    wateringFrequency: 1,
    nativeRegion: 'Arabian Peninsula and widely cultivated',
    tradeStatus: 0,
    idealTemp: '55-80°F (13-27°C)',
    sunlight: 4,
    description: 'Rosette succulent with thick, fleshy tapering leaves edged with small teeth; inner gel is medicinal.',
    idealConditions: 'Arid/subtropical; sandy well-draining soil; bright light to full sun.',
    careTips: 'Water rarely — deeply but infrequently, allowing soil to dry between waterings. Needs bright light and good drainage; overwatering causes root rot. Common mistakes: keeping in low light and overwatering.',
    isEndangered: false,
    isEdible: true,
    isPoisonous: false,
    uniqueFacts: 'Inner leaf gel used topically for burns and skin care.',
    imageURL: '0'
  },
  {
    genus: 'Aspidistra',
    species: 'elatior',
    commonName: 'Cast Iron Plant',
    cycle: 'perennial',
    wateringFrequency: 2,
    nativeRegion: 'East Asia',
    tradeStatus: 0,
    idealTemp: '50-75°F (10-24°C)',
    sunlight: 0,
    description: 'Tough, strap-like dark green leaves arising from rhizomes; exceptionally tolerant.',
    idealConditions: 'Shade to low light; humus-rich, well-draining soil; cool to moderate indoor temps.',
    careTips: 'Water occasionally — allow some drying between waterings. Thrives in low light and tolerates neglect; avoid intense sun. Common mistakes: overexposure to direct sun which scorches leaves.',
    isEndangered: false,
    isEdible: false,
    isPoisonous: false,
    uniqueFacts: 'Named for its ability to survive neglect and poor light conditions.',
    imageURL: '0'
  },
  {
    genus: 'Maranta',
    species: 'leuconeura',
    commonName: 'Prayer Plant',
    cycle: 'perennial',
    wateringFrequency: 3,
    nativeRegion: 'Tropical Americas (Brazil)',
    tradeStatus: 0,
    idealTemp: '60-80°F (16-27°C)',
    sunlight: 1,
    description: 'Oval patterned leaves with striking markings; leaves fold upward at night (prayer-like).',
    idealConditions: 'Humid, low-light understory; rich, moisture-retentive soil; warm temps.',
    careTips: 'Keep evenly moist and provide high humidity. Prefers low to medium indirect light; avoid hard tap water that can cause leaf tip browning. Common mistakes: letting soil dry out and low humidity causing brown edges.',
    isEndangered: false,
    isEdible: false,
    isPoisonous: false,
    uniqueFacts: 'Displays nyctinasty — leaves fold up at night like hands in prayer.',
    imageURL: '0'
  },
  {
    genus: 'Hedera',
    species: 'helix',
    commonName: 'English Ivy',
    cycle: 'perennial',
    wateringFrequency: 3,
    nativeRegion: 'Europe and Western Asia',
    tradeStatus: 0,
    idealTemp: '50-70°F (10-21°C)',
    sunlight: 2,
    description: 'Evergreen climbing vine with lobed, glossy leaves; useful as groundcover or climber.',
    idealConditions: 'Cool, moist sites; fertile well-draining soil; partial to full shade.',
    careTips: 'Water weekly and keep soil slightly moist. Prefers cooler indoor temps and moderate humidity. Common mistakes: overwatering and exposure to intense sun causing leaf scorch.',
    isEndangered: false,
    isEdible: false,
    isPoisonous: true,
    uniqueFacts: 'Can be invasive outdoors in some climates.',
    imageURL: '0'
  },
  {
    genus: 'Philodendron',
    species: 'hederaceum',
    commonName: 'Philodendron (Heartleaf)',
    cycle: 'perennial',
    wateringFrequency: 2,
    nativeRegion: 'Tropical Americas',
    tradeStatus: 0,
    idealTemp: '65-80°F (18-27°C)',
    sunlight: 2,
    description: 'Trailing vine with glossy, heart-shaped leaves; many cultivars and variegated forms.',
    idealConditions: 'Tropical understory; bright indirect light; rich, well-draining soil.',
    careTips: 'Water occasionally — allow topsoil to dry slightly between waterings. Tolerant of lower light but prefers humidity; avoid overwatering. Common mistakes: placing in cold drafts and overwatering.',
    isEndangered: false,
    isEdible: false,
    isPoisonous: true,
    uniqueFacts: 'Very easy to propagate from stem cuttings.',
    imageURL: '0'
  },
  {
    genus: 'Strelitzia',
    species: 'reginae',
    commonName: 'Bird of Paradise',
    cycle: 'perennial',
    wateringFrequency: 4,
    nativeRegion: 'South Africa',
    tradeStatus: 0,
    idealTemp: '65-75°F (18-24°C)',
    sunlight: 5,
    description: 'Large banana-like leaves with dramatic orange and blue bird-like flowers on tall stalks.',
    idealConditions: 'Subtropical; bright light to full sun; rich, well-draining soil.',
    careTips: 'Water frequently during growth to keep soil evenly moist. Needs bright light and warmth to bloom; common mistakes include insufficient light and inconsistent watering.',
    isEndangered: false,
    isEdible: false,
    isPoisonous: false,
    uniqueFacts: 'Showy flowers resemble the head of a tropical bird and are long-lasting.',
    imageURL: '0'
  },
  {
    genus: 'Dypsis',
    species: 'lutescens',
    commonName: 'Areca Palm',
    cycle: 'perennial',
    wateringFrequency: 3,
    nativeRegion: 'Madagascar',
    tradeStatus: 0,
    idealTemp: '65-75°F (18-24°C)',
    sunlight: 3,
    description: 'Clumping palm with feathery, arching pinnate fronds on thin stems; popular indoor palm.',
    idealConditions: 'Tropical/subtropical; bright indirect light; well-draining, humus-rich soil.',
    careTips: 'Keep soil slightly moist — water weekly. Prefers humidity and indirect light; avoid cold drafts. Common mistakes: overwatering and low humidity causing brown leaflet tips.',
    isEndangered: false,
    isEdible: false,
    isPoisonous: false,
    uniqueFacts: 'Commonly used as an indoor air-purifying plant.',
    imageURL: '0'
  },
  {
    genus: 'Peperomia',
    species: 'spp.',
    commonName: 'Peperomia (Watermelon/Ripple)',
    cycle: 'perennial',
    wateringFrequency: 2,
    nativeRegion: 'Tropical Americas',
    tradeStatus: 0,
    idealTemp: '65-80°F (18-27°C)',
    sunlight: 2,
    description: 'Compact plants with diverse leaf shapes and textures; many have patterned or succulent-like leaves.',
    idealConditions: 'Bright indirect light; well-draining potting mix; moderate humidity.',
    careTips: 'Water occasionally — allow topsoil to dry between waterings. Avoid soggy soil and provide bright indirect light. Common mistakes: overwatering and insufficient light.',
    isEndangered: false,
    isEdible: false,
    isPoisonous: false,
    uniqueFacts: 'Many species are ideal for small pots and terrariums.',
    imageURL: '0'
  },
  {
    genus: 'Dracaena',
    species: 'fragrans',
    commonName: 'Dracaena (Corn Plant)',
    cycle: 'perennial',
    wateringFrequency: 2,
    nativeRegion: 'Tropical Africa',
    tradeStatus: 0,
    idealTemp: '65-75°F (18-24°C)',
    sunlight: 2,
    description: 'Tree-like cane with arching, sword-shaped leaves often variegated; tolerant houseplant.',
    idealConditions: 'Bright indirect light to medium; well-draining soil; moderate humidity.',
    careTips: 'Water occasionally — allow top inch to dry between waterings. Sensitive to fluoride in water; avoid overwatering. Common mistakes: overwatering and low light causing leggy growth.',
    isEndangered: false,
    isEdible: false,
    isPoisonous: true,
    uniqueFacts: 'Leaves resemble corn foliage, hence its common name.',
    imageURL: '0'
  },
  {
    genus: 'Nephrolepis',
    species: 'exaltata',
    commonName: 'Boston Fern',
    cycle: 'perennial',
    wateringFrequency: 4,
    nativeRegion: 'Tropical regions worldwide',
    tradeStatus: 0,
    idealTemp: '60-75°F (16-24°C)',
    sunlight: 1,
    description: 'Lush arching fronds composed of many fine leaflets; classic hanging-basket fern.',
    idealConditions: 'Humid, shaded understory; rich, evenly moist soil; indirect light.',
    careTips: 'Keep soil consistently moist and provide high humidity. Avoid direct sun and dry indoor air. Common mistakes: letting soil dry out and exposing to hot, dry conditions.',
    isEndangered: false,
    isEdible: false,
    isPoisonous: false,
    uniqueFacts: 'Very popular as a hanging basket due to cascading fronds.',
    imageURL: '0'
  },
  {
    genus: 'Phalaenopsis',
    species: 'spp.',
    commonName: 'Orchid (Phalaenopsis)',
    cycle: 'perennial',
    wateringFrequency: 3,
    nativeRegion: 'Southeast Asia and Australia',
    tradeStatus: 0,
    idealTemp: '65-80°F (18-27°C)',
    sunlight: 2,
    description: 'Elegant orchids with broad, leathery leaves and long spikes of flat, moth-like blooms.',
    idealConditions: 'Epiphytic: airy, well-draining orchid mix; bright indirect light; moderate humidity.',
    careTips: 'Water weekly to every 10 days, allowing medium to dry slightly between waterings. Provide bright indirect light and good air circulation; avoid planting in regular potting soil. Common mistakes: overwatering and poor drainage.',
    isEndangered: false,
    isEdible: false,
    isPoisonous: false,
    uniqueFacts: 'Among the easiest orchids to grow and widely sold as houseplants.',
    imageURL: '0'
  },
  {
    genus: 'Schlumbergera',
    species: 'bridgesii',
    commonName: 'Christmas Cactus',
    cycle: 'perennial',
    wateringFrequency: 2,
    nativeRegion: 'Brazil (coastal forests)',
    tradeStatus: 0,
    idealTemp: '60-70°F (15-21°C)',
    sunlight: 2,
    description: 'Flattened segmented stems with bright tubular flowers that often bloom around winter holidays.',
    idealConditions: 'Humid, sheltered forest understory; well-draining cactus/epiphyte mix; bright indirect light.',
    careTips: 'Water occasionally — keep slightly moist during growth and reduce after flowering. Prefers bright indirect light and cooler temps to encourage blooms. Common mistakes: overwatering and exposing to frost.',
    isEndangered: false,
    isEdible: false,
    isPoisonous: false,
    uniqueFacts: 'Blooms commonly coincide with short days around winter, hence its common name.',
    imageURL: '0'
  },
  {
    genus: 'Calathea',
    species: 'spp.',
    commonName: 'Calathea (GoEater Plant)',
    cycle: 'perennial',
    wateringFrequency: 4,
    nativeRegion: 'Tropical Americas (Brazil)',
    tradeStatus: 0,
    idealTemp: '65-80°F (18-27°C)',
    sunlight: 1,
    description: 'Striking patterned foliage with bold markings and variegation; leaves often move at night.',
    idealConditions: 'Humid tropical understory; rich, moisture-retentive but well-draining soil; low to medium light.',
    careTips: 'Keep consistently moist and provide high humidity. Prefers low to medium indirect light; sensitive to hard water and fluoride. Common mistakes: dry air and inconsistent watering causing brown leaf edges.',
    isEndangered: false,
    isEdible: false,
    isPoisonous: false,
    uniqueFacts: 'Many species show nyctinastic leaf movement (folding at night).',
    imageURL: '0'
  },
  {
    genus: 'Hoya',
    species: 'carnosa',
    commonName: 'Hoya (Wax Plant)',
    cycle: 'perennial',
    wateringFrequency: 1,
    nativeRegion: 'Southeast Asia and Australasia',
    tradeStatus: 0,
    idealTemp: '60-85°F (16-29°C)',
    sunlight: 3,
    description: 'Vining succulent with thick waxy leaves and clusters of star-shaped fragrant flowers.',
    idealConditions: 'Tropical/subtropical; well-draining mix; bright indirect light; good airflow.',
    careTips: 'Water rarely — allow to dry between waterings. Thrives in bright indirect light; avoid soggy soil. Common mistakes: overwatering and low light preventing blooms.',
    isEndangered: false,
    isEdible: false,
    isPoisonous: false,
    uniqueFacts: 'Flowers often form in umbels and can be long-lasting and fragrant.',
    imageURL: '0'
  },
  {
    genus: 'Senecio',
    species: 'rowleyanus',
    commonName: 'String of Pearls',
    cycle: 'perennial',
    wateringFrequency: 1,
    nativeRegion: 'Southern Africa',
    tradeStatus: 0,
    idealTemp: '60-80°F (16-27°C)',
    sunlight: 4,
    description: 'Trailing stems with bead-like, fleshy leaves resembling peas; excellent in hanging baskets.',
    idealConditions: 'Arid to semi-arid; very well-draining gritty soil; bright light to full sun.',
    careTips: 'Water rarely — let soil dry between waterings. Provide bright light for compact growth; avoid overwatering. Common mistakes: keeping soil too moist and insufficient light causing leggy growth.',
    isEndangered: false,
    isEdible: false,
    isPoisonous: true,
    uniqueFacts: 'Its spherical leaves store water, giving a distinctive \'pearl\' appearance.',
    imageURL: '0'
  },
  {
    genus: 'Ceropegia',
    species: 'woodii',
    commonName: 'String of Hearts',
    cycle: 'perennial',
    wateringFrequency: 1,
    nativeRegion: 'South Africa',
    tradeStatus: 0,
    idealTemp: '60-80°F (16-27°C)',
    sunlight: 4,
    description: 'Delicate trailing vines with small, heart-shaped leaves often variegated; great for hanging pots.',
    idealConditions: 'Well-draining soil; bright indirect light to some direct sun; arid to semi-arid environments.',
    careTips: 'Water rarely — allow soil to dry between waterings. Prefers bright light; avoid prolonged moisture. Common mistakes: overwatering and lack of light.',
    isEndangered: false,
    isEdible: false,
    isPoisonous: false,
    uniqueFacts: 'Makes a graceful trailing display and is easily propagated from cuttings.',
    imageURL: '0'
  },
  {
    genus: 'Pachira',
    species: 'aquatica',
    commonName: 'Money Tree',
    cycle: 'perennial',
    wateringFrequency: 3,
    nativeRegion: 'Central and South America',
    tradeStatus: 0,
    idealTemp: '65-80°F (18-27°C)',
    sunlight: 3,
    description: 'Tree with palmate leaves (5+ leaflets) and often braided trunk when sold as houseplant.',
    idealConditions: 'Tropical regions; bright indirect light; well-draining soil with consistent moisture.',
    careTips: 'Water weekly — allow topsoil to dry slightly between waterings. Prefers bright indirect light and moderate humidity. Common mistakes: overwatering and low light.',
    isEndangered: false,
    isEdible: false,
    isPoisonous: false,
    uniqueFacts: 'Often braided and marketed as a symbol of luck and prosperity.',
    imageURL: '0'
  },
  {
    genus: 'Echeveria',
    species: 'spp.',
    commonName: 'Echeveria',
    cycle: 'perennial',
    wateringFrequency: 1,
    nativeRegion: 'Mexico and Central America',
    tradeStatus: 0,
    idealTemp: '50-80°F (10-27°C)',
    sunlight: 5,
    description: 'Rosette-forming succulents with fleshy leaves in pastel colors and compact habit.',
    idealConditions: 'Arid, well-draining gritty soil; full sun to bright light; xeric biomes.',
    careTips: 'Water rarely — deep infrequent watering and allow soil to dry completely between waterings. Provide bright light to maintain compact form. Common mistakes: overwatering and low light causing stretching.',
    isEndangered: false,
    isEdible: false,
    isPoisonous: false,
    uniqueFacts: 'Many cultivars prized for colorful rosette shapes and compact size.',
    imageURL: '0'
  },
  {
    genus: 'Haworthia',
    species: 'spp.',
    commonName: 'Haworthia',
    cycle: 'perennial',
    wateringFrequency: 1,
    nativeRegion: 'Southern Africa',
    tradeStatus: 0,
    idealTemp: '60-85°F (16-29°C)',
    sunlight: 3,
    description: 'Small rosette succulents with thick, often banded leaves; compact and slow-growing.',
    idealConditions: 'Well-draining soil; bright indirect light to some sun; arid biomes.',
    careTips: 'Water rarely — allow soil to dry between waterings. Avoid intense midday sun for some species. Common mistakes: overwatering and poor drainage.',
    isEndangered: false,
    isEdible: false,
    isPoisonous: false,
    uniqueFacts: 'Many species form small offsets, creating clusters over time.',
    imageURL: '0'
  },
  {
    genus: 'Sempervivum',
    species: 'tectorum',
    commonName: 'Sempervivum (Hens and Chicks)',
    cycle: 'perennial',
    wateringFrequency: 1,
    nativeRegion: 'Europe (mountain regions)',
    tradeStatus: 0,
    idealTemp: '20-85°F (-6-29°C) depending on cultivar',
    sunlight: 5,
    description: 'Rosette-forming hardy succulent that produces offsets (chicks) around a mother rosette.',
    idealConditions: 'Well-draining rocky soil; full sun; alpine/rocky biomes.',
    careTips: 'Water rarely — provide excellent drainage and full sun. Common mistakes: overwatering and heavy soils.',
    isEndangered: false,
    isEdible: false,
    isPoisonous: false,
    uniqueFacts: 'Extremely cold-hardy succulents used in rock gardens and containers.',
    imageURL: '0'
  },
  {
    genus: 'Sedum',
    species: 'spp.',
    commonName: 'Sedum (Stonecrops)',
    cycle: 'perennial',
    wateringFrequency: 1,
    nativeRegion: 'Northern Hemisphere',
    tradeStatus: 0,
    idealTemp: '40-85°F (4-29°C) depending on species',
    sunlight: 5,
    description: 'Succulent leaves on trailing or upright stems; often produces clusters of star-shaped flowers.',
    idealConditions: 'Well-draining soils; full sun to partial shade; xeric to temperate biomes.',
    careTips: 'Water rarely — drought tolerant and prefers bright light. Avoid excessive moisture. Common mistakes: overwatering and insufficient light.',
    isEndangered: false,
    isEdible: false,
    isPoisonous: false,
    uniqueFacts: 'Many sedums are used in green roofs for drought tolerance.',
    imageURL: '0'
  },
  {
    genus: 'Kalanchoe',
    species: 'spp.',
    commonName: 'Kalanchoe',
    cycle: 'perennial',
    wateringFrequency: 2,
    nativeRegion: 'Madagascar and tropical Africa',
    tradeStatus: 0,
    idealTemp: '60-85°F (16-29°C)',
    sunlight: 4,
    description: 'Succulent leaves (various textures) and clusters of small colorful flowers on stalks.',
    idealConditions: 'Well-draining soil; bright light to full sun; arid to subtropical biomes.',
    careTips: 'Water occasionally — allow soil to dry between waterings. Provide bright light to encourage flowering. Common mistakes: overwatering and low light preventing blooms.',
    isEndangered: false,
    isEdible: false,
    isPoisonous: true,
    uniqueFacts: 'Popular as a gift plant due to long-lasting flower clusters.',
    imageURL: '0'
  },
  {
    genus: 'Gasteria',
    species: 'spp.',
    commonName: 'Gasteria',
    cycle: 'perennial',
    wateringFrequency: 1,
    nativeRegion: 'South Africa',
    tradeStatus: 0,
    idealTemp: '50-80°F (10-27°C)',
    sunlight: 2,
    description: 'Succulent with thick, tongue-shaped leaves often mottled or rough-textured; forms small clumps.',
    idealConditions: 'Well-draining soil; bright indirect light to partial shade; arid regions.',
    careTips: 'Water rarely — allow soil to dry between waterings. Avoid intense midday sun for many species. Common mistakes: overwatering and cold exposure.',
    isEndangered: false,
    isEdible: false,
    isPoisonous: false,
    uniqueFacts: 'Leaves often have swollen shapes resembling a \'stomach\' (gaster).',
    imageURL: '0'
  },
  {
    genus: 'Lithops',
    species: 'spp.',
    commonName: 'Lithops (Living Stones)',
    cycle: 'perennial',
    wateringFrequency: 0,
    nativeRegion: 'Southern Africa',
    tradeStatus: 0,
    idealTemp: '60-90°F (16-32°C)',
    sunlight: 5,
    description: 'Small, stone-like succulents composed of two thick fused leaves that resemble rocks.',
    idealConditions: 'Extremely well-draining gritty mix; full sun; arid desert biomes.',
    careTips: 'Water almost never — only in active growth periods and very sparingly (never to rarely). Avoid watering during dormancy. Common mistakes: overwatering causing rot.',
    isEndangered: false,
    isEdible: false,
    isPoisonous: false,
    uniqueFacts: 'Evolved to resemble stones as camouflage from herbivores.',
    imageURL: '0'
  },
  {
    genus: 'Mammillaria',
    species: 'spp.',
    commonName: 'Mammillaria (Pincushion Cacti)',
    cycle: 'perennial',
    wateringFrequency: 1,
    nativeRegion: 'Mexico and Americas',
    tradeStatus: 0,
    idealTemp: '50-90°F (10-32°C)',
    sunlight: 5,
    description: 'Small globular cacti with numerous tubercles and radial spines; often form clusters and ringed flowers.',
    idealConditions: 'Well-draining cactus mix; full sun to bright light; arid environments.',
    careTips: 'Water rarely during growing season and very sparingly in winter. Provide bright sun and excellent drainage. Common mistakes: overwatering and poor drainage.',
    isEndangered: false,
    isEdible: false,
    isPoisonous: false,
    uniqueFacts: 'Many species produce attractive colorful flowers around the crown.',
    imageURL: '0'
  },
  {
    genus: 'Opuntia',
    species: 'spp.',
    commonName: 'Opuntia (Prickly Pear)',
    cycle: 'perennial',
    wateringFrequency: 1,
    nativeRegion: 'Americas',
    tradeStatus: 0,
    idealTemp: '50-95°F (10-35°C) depending on species',
    sunlight: 5,
    description: 'Pad-like stems (pads) with spines and glochids; some species produce edible fruits.',
    idealConditions: 'Full sun; well-draining sandy soil; arid to semi-arid biomes.',
    careTips: 'Water rarely — provide lots of direct light and excellent drainage. Protect from cold and excess moisture. Common mistakes: overwatering and cold exposure.',
    isEndangered: false,
    isEdible: true,
    isPoisonous: false,
    uniqueFacts: 'Some species bear edible fruits called tunas used in cuisine.',
    imageURL: '0'
  },
  {
    genus: 'Ferocactus',
    species: 'spp.',
    commonName: 'Barrel Cactus',
    cycle: 'perennial',
    wateringFrequency: 1,
    nativeRegion: 'North and Central America (deserts)',
    tradeStatus: 0,
    idealTemp: '50-100°F (10-38°C)',
    sunlight: 5,
    description: 'Large cylindrical or barrel-shaped cacti with prominent ribs and stout spines.',
    idealConditions: 'Full sun; extremely well-draining soil; desert biome.',
    careTips: 'Water rarely — deep but infrequent during growing season and very sparingly in winter. Needs bright light and excellent drainage. Common mistakes: overwatering and heavy soils.',
    isEndangered: false,
    isEdible: false,
    isPoisonous: false,
    uniqueFacts: 'Some barrel cacti can live for many decades.',
    imageURL: '0'
  },
  {
    genus: 'Epipremnum',
    species: 'aureum \'Neon\'',
    commonName: 'Golden Pothos (Neon)',
    cycle: 'perennial',
    wateringFrequency: 2,
    nativeRegion: 'Southeast Asia',
    tradeStatus: 0,
    idealTemp: '65-85°F (18-29°C)',
    sunlight: 3,
    description: 'Trailing vine with bright chartreuse to yellow-green leaves; similar habit to standard pothos.',
    idealConditions: 'Tropical understory; bright indirect light for best color; well-draining soil.',
    careTips: 'Water weekly allowing topsoil to dry slightly between waterings. Prefers bright indirect light to maintain neon color; tolerant of lower light. Common mistakes: overwatering and direct hot sun.',
    isEndangered: false,
    isEdible: false,
    isPoisonous: true,
    uniqueFacts: 'Neon cultivar prized for its vivid chartreuse foliage.',
    imageURL: '0'
  },
  {
    genus: 'Various',
    species: 'various',
    commonName: 'Crested Succulents',
    cycle: 'perennial',
    wateringFrequency: 1,
    nativeRegion: 'Varied',
    tradeStatus: 0,
    idealTemp: '50-85°F (10-29°C)',
    sunlight: 4,
    description: 'Unusual fused or fan-shaped growth forms (crested) of various succulent species creating sculptural shapes.',
    idealConditions: 'Depends on parent species; generally well-draining soil and bright light.',
    careTips: 'Water rarely and according to parent-species needs. Provide bright light and excellent drainage; avoid overwatering. Common mistakes: treating them like non-succulents and overwatering.',
    isEndangered: false,
    isEdible: false,
    isPoisonous: 'varies',
    uniqueFacts: 'Cresting is a mutation that creates unique, collectible plant forms.',
    imageURL: '0'
  },
  {
    genus: 'Opuntia',
    species: 'microdasys',
    commonName: 'Paddle Cactus',
    cycle: 'perennial',
    wateringFrequency: 1,
    nativeRegion: 'Mexico',
    tradeStatus: 0,
    idealTemp: '50-95°F (10-35°C)',
    sunlight: 5,
    description: 'Pad-forming cactus covered in dense clusters of glochids (hair-like spines); pads are oval and erect.',
    idealConditions: 'Full sun; very well-draining sandy soil; arid biome.',
    careTips: 'Water rarely and provide full sun. Protect from cold and excess moisture. Common mistakes: overwatering and handling without gloves due to glochids.',
    isEndangered: false,
    isEdible: false,
    isPoisonous: false,
    uniqueFacts: 'Glochids detach easily and can be irritating to skin.',
    imageURL: '0'
  },
  {
    genus: 'Tillandsia',
    species: 'spp.',
    commonName: 'Air Plants (Tillandsia)',
    cycle: 'perennial',
    wateringFrequency: 2,
    nativeRegion: 'Americas',
    tradeStatus: 0,
    idealTemp: '50-90°F (10-32°C)',
    sunlight: 3,
    description: 'Epiphytic plants lacking traditional soil roots; absorb moisture and nutrients through leaves.',
    idealConditions: 'Epiphytic on trees/rocks; bright indirect light or morning sun; airy conditions.',
    careTips: 'Water occasionally via soaking or heavy misting and allow good airflow to dry between waterings (weekly to biweekly). Avoid keeping them wet without airflow. Common mistakes: too little airflow causing rot or letting them desiccate completely.',
    isEndangered: false,
    isEdible: false,
    isPoisonous: false,
    uniqueFacts: 'Absorb water and nutrients primarily through specialized leaf trichomes rather than roots.',
    imageURL: '0'
  },
  {
    genus: 'Crassula',
    species: 'muscosa',
    commonName: 'Crassula Muscosa (Watch Chain)',
    cycle: 'perennial',
    wateringFrequency: 1,
    nativeRegion: 'South Africa',
    tradeStatus: 0,
    idealTemp: '60-80°F (16-27°C)',
    sunlight: 3,
    description: 'Dense, branching succulent stems with tiny scale-like leaves creating a watch-chain appearance.',
    idealConditions: 'Well-draining soil; bright indirect light to some sun; arid biomes.',
    careTips: 'Water rarely — allow soil to dry between waterings. Avoid overwatering. Common mistakes: excessive moisture leading to rot.',
    isEndangered: false,
    isEdible: false,
    isPoisonous: false,
    uniqueFacts: 'Forms intricate dense mats attractive for collectors of unusual succulents.',
    imageURL: '0'
  },
  {
    genus: 'Aloe',
    species: 'aristata',
    commonName: 'Aloe Aristata (Lace Aloe)',
    cycle: 'perennial',
    wateringFrequency: 1,
    nativeRegion: 'South Africa',
    tradeStatus: 0,
    idealTemp: '50-80°F (10-27°C)',
    sunlight: 4,
    description: 'Small rosette succulent with toothed leaf margins and small white spots; forms offsets.',
    idealConditions: 'Well-draining gritty soil; bright light to partial sun; arid regions.',
    careTips: 'Water rarely and provide bright light. Allow soil to dry between waterings. Common mistakes: overwatering and cold exposure.',
    isEndangered: false,
    isEdible: false,
    isPoisonous: false,
    uniqueFacts: 'Compact cultivar prized for lace-like leaf edges.',
    imageURL: '0'
  },
  {
    genus: 'Agave',
    species: 'var.',
    commonName: 'Agave (Small Varieties)',
    cycle: 'perennial',
    wateringFrequency: 1,
    nativeRegion: 'Americas (Mexico)',
    tradeStatus: 0,
    idealTemp: '50-90°F (10-32°C)',
    sunlight: 5,
    description: 'Rosette succulents with stiff, often spiny leaves forming architectural forms.',
    idealConditions: 'Full sun; extremely well-draining soil; arid to semi-arid biomes.',
    careTips: 'Water rarely and provide full sun and excellent drainage. Common mistakes: overwatering and planting in heavy soils.',
    isEndangered: false,
    isEdible: false,
    isPoisonous: false,
    uniqueFacts: 'Many agaves are monocarpic — they flower once and then die, producing offsets.',
    imageURL: '0'
  },
  {
    genus: 'Euphorbia',
    species: 'tirucalli',
    commonName: 'Pencil Cactus (Euphorbia tirucalli)',
    cycle: 'perennial',
    wateringFrequency: 1,
    nativeRegion: 'Tropical Africa',
    tradeStatus: 0,
    idealTemp: '65-85°F (18-29°C)',
    sunlight: 5,
    description: 'Succulent, pencil-like stems that are smooth and cylindrical with minimal leaves.',
    idealConditions: 'Full sun to bright light; well-draining soil; arid to semi-arid biomes.',
    careTips: 'Water rarely and provide bright light. Be cautious: milky sap is irritating. Common mistakes: overwatering and contact with sap causing skin/eye irritation.',
    isEndangered: false,
    isEdible: false,
    isPoisonous: true,
    uniqueFacts: 'Milky latex sap is caustic and used traditionally for various applications.',
    imageURL: '0'
  },
  {
    genus: 'Mammillaria',
    species: 'elongata',
    commonName: 'Fishhook Cactus (Mammillaria elongata)',
    cycle: 'perennial',
    wateringFrequency: 1,
    nativeRegion: 'Mexico',
    tradeStatus: 0,
    idealTemp: '50-90°F (10-32°C)',
    sunlight: 5,
    description: 'Cluster-forming small cylindrical stems with hooked spines; often forms carpets of offsets.',
    idealConditions: 'Full sun; very well-draining soil; arid biome.',
    careTips: 'Water rarely and provide bright light. Avoid excess moisture. Common mistakes: overwatering and poor drainage.',
    isEndangered: false,
    isEdible: false,
    isPoisonous: false,
    uniqueFacts: 'Named for its curved, fishhook-like spines.',
    imageURL: '0'
  },
  {
    genus: 'Philodendron',
    species: 'erubescens \'Pink Princess\'',
    commonName: 'Pink Princess Philodendron',
    cycle: 'perennial',
    wateringFrequency: 3,
    nativeRegion: 'Tropical Americas',
    tradeStatus: 0,
    idealTemp: '65-80°F (18-27°C)',
    sunlight: 3,
    description: 'Vining philodendron with dark leaves splashed with pink variegation; striking ornamental foliage.',
    idealConditions: 'Tropical understory; bright indirect light to encourage variegation; well-draining soil.',
    careTips: 'Water weekly — allow topsoil to dry slightly. Requires bright indirect light to maintain pink variegation. Common mistakes: low light causing loss of variegation and overwatering.',
    isEndangered: false,
    isEdible: false,
    isPoisonous: true,
    uniqueFacts: 'Pink variegation is highly sought after and often commands high prices.',
    imageURL: '0'
  },
  {
    genus: 'Thaumatophyllum',
    species: 'bipinnatifidum',
    commonName: 'Split Leaf Philodendron',
    cycle: 'perennial',
    wateringFrequency: 3,
    nativeRegion: 'South America (Brazil)',
    tradeStatus: 0,
    idealTemp: '65-85°F (18-29°C)',
    sunlight: 3,
    description: 'Large, deeply lobed leaves on a robust tropical plant; can become sizable indoor specimen.',
    idealConditions: 'Tropical understory; bright indirect light; rich, well-draining soil.',
    careTips: 'Water weekly and provide humidity. Avoid direct harsh sun which can scorch large leaves. Common mistakes: overwatering and low humidity causing brown edges.',
    isEndangered: false,
    isEdible: false,
    isPoisonous: true,
    uniqueFacts: 'Leaves can reach several feet across on mature plants.',
    imageURL: '0'
  },
  {
    genus: 'Alocasia',
    species: 'spp.',
    commonName: 'Alocasia (Elephant Ear)',
    cycle: 'perennial',
    wateringFrequency: 4,
    nativeRegion: 'Tropical Asia and Australia',
    tradeStatus: 0,
    idealTemp: '65-85°F (18-29°C)',
    sunlight: 3,
    description: 'Dramatic, arrow or heart-shaped large leaves often with striking veins and glossy surfaces.',
    idealConditions: 'Humid, warm tropical understory; rich, moisture-retentive soil; indirect light.',
    careTips: 'Keep soil consistently moist and provide high humidity. Prefers bright indirect light; avoid cold drafts. Common mistakes: letting soil dry out and low humidity causing leaf drop.',
    isEndangered: false,
    isEdible: false,
    isPoisonous: true,
    uniqueFacts: 'Leaves often used as focal points in tropical plantings.',
    imageURL: '0'
  },
  {
    genus: 'Colocasia',
    species: 'spp.',
    commonName: 'Colocasia (Taro relatives)',
    cycle: 'perennial',
    wateringFrequency: 4,
    nativeRegion: 'Tropical Asia',
    tradeStatus: 0,
    idealTemp: '65-85°F (18-29°C)',
    sunlight: 4,
    description: 'Large, heart-shaped glossy leaves often grown for ornamental foliage or edible corms outdoors.',
    idealConditions: 'Wet, boggy soils in tropics; rich, moisture-retentive soil; partial shade to sun.',
    careTips: 'Water frequently and keep consistently moist. Many are grown outdoors for edible corms; avoid frost. Common mistakes: allowing soil to dry and frost exposure.',
    isEndangered: false,
    isEdible: true,
    isPoisonous: false,
    uniqueFacts: 'Some species are cultivated for edible corms (taro) though raw plant can be irritating unless cooked.',
    imageURL: '0'
  },
  {
    genus: 'Syngonium',
    species: 'podophyllum',
    commonName: 'Syngonium (Arrowhead Plant)',
    cycle: 'perennial',
    wateringFrequency: 3,
    nativeRegion: 'Central and South America',
    tradeStatus: 0,
    idealTemp: '60-80°F (16-27°C)',
    sunlight: 2,
    description: 'Arrowhead-shaped leaves that change form as plant matures; trailing or climbing habit.',
    idealConditions: 'Tropical understory; bright indirect light to medium; well-draining soil.',
    careTips: 'Water weekly — allow topsoil to dry slightly. Prefers humidity and indirect light. Common mistakes: overwatering and low light causing leggy growth.',
    isEndangered: false,
    isEdible: false,
    isPoisonous: true,
    uniqueFacts: 'Juvenile and adult leaf forms differ in shape and texture.',
    imageURL: '0'
  },
  {
    genus: 'Dieffenbachia',
    species: 'spp.',
    commonName: 'Dieffenbachia (Dumb Cane)',
    cycle: 'perennial',
    wateringFrequency: 3,
    nativeRegion: 'Tropical Americas',
    tradeStatus: 0,
    idealTemp: '65-80°F (18-27°C)',
    sunlight: 2,
    description: 'Large patterned leaves on cane-like stems; variegated cultivars common.',
    idealConditions: 'Tropical understory; bright indirect light; rich, well-draining soil.',
    careTips: 'Water weekly and keep evenly moist but not waterlogged. Sensitive to cold and drafts; sap can be irritating—avoid ingestion. Common mistakes: overwatering and cold stress causing leaf drop.',
    isEndangered: false,
    isEdible: false,
    isPoisonous: true,
    uniqueFacts: 'Sap can cause swelling and pain if ingested, hence the \'dumb cane\' name.',
    imageURL: '0'
  },
  // New plants from CSV data
  {
    genus: 'Begonia',
    species: 'rex',
    commonName: 'Rex Begonia',
    cycle: 'perennial',
    wateringFrequency: 3,
    nativeRegion: 'India and Southeast Asia',
    tradeStatus: 0,
    idealTemp: '60-75°F (16-24°C)',
    sunlight: 2,
    description: 'Colorful foliage plant with large, textured leaves in shades of green, red, and silver.',
    idealConditions: 'Humid, shaded tropical regions; loose, well-draining soil; bright indirect light.',
    careTips: 'Water weekly — keep soil slightly moist but not soggy (weekly). Requires high humidity and indirect light. Common mistakes: low humidity and overwatering causing leaf drop.',
    isEndangered: false,
    isEdible: false,
    isPoisonous: true,
    uniqueFacts: 'Grown primarily for its ornamental leaves rather than flowers.',
    imageURL: '0'
  },
  {
    genus: 'Anthurium',
    species: 'andreanum',
    commonName: 'Flamingo Flower',
    cycle: 'perennial',
    wateringFrequency: 4,
    nativeRegion: 'Colombia and Ecuador',
    tradeStatus: 0,
    idealTemp: '65-80°F (18-27°C)',
    sunlight: 3,
    description: 'Glossy heart-shaped leaves and bright waxy spathes surrounding a central spadix.',
    idealConditions: 'Tropical humid forests; rich, well-draining soil; bright indirect light.',
    careTips: 'Keep soil moist but not waterlogged (frequently). Likes humidity and indirect sunlight. Common mistakes: dry air and low light reducing blooms.',
    isEndangered: false,
    isEdible: false,
    isPoisonous: true,
    uniqueFacts: 'Its bright spathe is often mistaken for the flower itself.',
    imageURL: '0'
  },
  {
    genus: 'Alocasia',
    species: 'amazonica',
    commonName: 'African Mask Plant',
    cycle: 'perennial',
    wateringFrequency: 4,
    nativeRegion: 'Southeast Asia',
    tradeStatus: 0,
    idealTemp: '65-80°F (18-27°C)',
    sunlight: 2,
    description: 'Striking dark green leaves with prominent white veins and arrow-like shape.',
    idealConditions: 'Humid tropical forest floors; loose, airy soil; bright indirect light.',
    careTips: 'Water frequently to keep soil evenly moist (frequently). Requires high humidity and filtered light. Common mistakes: letting soil dry out and cold drafts causing dormancy.',
    isEndangered: false,
    isEdible: false,
    isPoisonous: true,
    uniqueFacts: 'Not actually African despite its name; native to Asia.',
    imageURL: '0'
  },
  {
    genus: 'Dieffenbachia',
    species: 'seguine',
    commonName: 'Dumb Cane',
    cycle: 'perennial',
    wateringFrequency: 3,
    nativeRegion: 'Tropical Americas',
    tradeStatus: 0,
    idealTemp: '65-80°F (18-27°C)',
    sunlight: 2,
    description: 'Large, variegated green leaves with cream or yellow markings on a thick cane-like stem.',
    idealConditions: 'Tropical understory; rich, moist soil; medium indirect light.',
    careTips: 'Water weekly or when topsoil dries slightly (weekly). Avoid overwatering and low light. Common mistakes: poor drainage and cold drafts.',
    isEndangered: false,
    isEdible: false,
    isPoisonous: true,
    uniqueFacts: 'Sap can irritate skin and temporarily numb mouth tissues.',
    imageURL: '0'
  },
  {
    genus: 'Sansevieria',
    species: 'trifasciata',
    commonName: 'Snake Plant',
    cycle: 'perennial',
    wateringFrequency: 1,
    nativeRegion: 'West Africa',
    tradeStatus: 0,
    idealTemp: '60-85°F (16-29°C)',
    sunlight: 2,
    description: 'Erect sword-like leaves banded in green and yellow; tough and architectural form.',
    idealConditions: 'Arid to semi-arid; sandy well-draining soil; tolerates low light.',
    careTips: 'Water rarely — once every few weeks (rarely). Extremely tolerant of neglect and low light. Common mistakes: overwatering causing root rot.',
    isEndangered: false,
    isEdible: false,
    isPoisonous: true,
    uniqueFacts: 'Produces oxygen even at night unlike most plants.',
    imageURL: '0'
  },
  {
    genus: 'Aglaonema',
    species: 'commutatum',
    commonName: 'Chinese Evergreen',
    cycle: 'perennial',
    wateringFrequency: 3,
    nativeRegion: 'Tropical and subtropical Asia',
    tradeStatus: 0,
    idealTemp: '65-80°F (18-27°C)',
    sunlight: 2,
    description: 'Broad, variegated leaves with patterns of silver, green, or red tones.',
    idealConditions: 'Warm, humid understory; fertile, well-draining soil; low to medium light.',
    careTips: 'Water weekly (weekly). Tolerates low light well; avoid cold temperatures. Common mistakes: exposure to drafts and soggy soil.',
    isEndangered: false,
    isEdible: false,
    isPoisonous: true,
    uniqueFacts: 'Often recommended as a good plant for low-light interiors.',
    imageURL: '0'
  },
  {
    genus: 'Schefflera',
    species: 'arboricola',
    commonName: 'Umbrella Plant',
    cycle: 'perennial',
    wateringFrequency: 3,
    nativeRegion: 'Taiwan and Hainan',
    tradeStatus: 0,
    idealTemp: '60-75°F (16-24°C)',
    sunlight: 3,
    description: 'Glossy, palmate leaves with several oval leaflets radiating from a single stem point.',
    idealConditions: 'Tropical/subtropical forest margins; well-draining soil; bright indirect light.',
    careTips: 'Water weekly (weekly). Prefers bright indirect light; avoid overwatering. Common mistakes: soggy soil leading to root rot.',
    isEndangered: false,
    isEdible: false,
    isPoisonous: true,
    uniqueFacts: 'Called \'umbrella plant\' for its radiating leaf clusters.',
    imageURL: '0'
  },
  {
    genus: 'Pilea',
    species: 'peperomioides',
    commonName: 'Chinese Money Plant',
    cycle: 'perennial',
    wateringFrequency: 2,
    nativeRegion: 'Yunnan, China',
    tradeStatus: 0,
    idealTemp: '60-75°F (16-24°C)',
    sunlight: 3,
    description: 'Small plant with round, coin-like leaves on upright stems; compact and decorative.',
    idealConditions: 'Cool, humid mountain regions; loose, well-draining soil; bright indirect light.',
    careTips: 'Water occasionally — when topsoil is dry (occasionally). Rotate regularly for even growth. Common mistakes: overwatering and low light causing leggy growth.',
    isEndangered: false,
    isEdible: false,
    isPoisonous: false,
    uniqueFacts: 'Often shared as \'friendship plants\' by passing on offshoots.',
    imageURL: '0'
  },
  {
    genus: 'Oxalis',
    species: 'triangularis',
    commonName: 'Purple Shamrock',
    cycle: 'perennial',
    wateringFrequency: 2,
    nativeRegion: 'South America',
    tradeStatus: 0,
    idealTemp: '60-75°F (16-24°C)',
    sunlight: 3,
    description: 'Triangular purple leaves and delicate pink or white flowers that close at night.',
    idealConditions: 'Partial sun to bright shade; well-draining soil; mild, humid climates.',
    careTips: 'Water occasionally — allow soil to dry slightly (occasionally). Goes dormant periodically. Common mistakes: overwatering during dormancy.',
    isEndangered: false,
    isEdible: false,
    isPoisonous: true,
    uniqueFacts: 'Folds leaves at night and opens them by day through light response.',
    imageURL: '0'
  },
  {
    genus: 'Tradescantia',
    species: 'zebrina',
    commonName: 'Wandering Jew',
    cycle: 'perennial',
    wateringFrequency: 3,
    nativeRegion: 'Mexico and Central America',
    tradeStatus: 0,
    idealTemp: '60-80°F (16-27°C)',
    sunlight: 3,
    description: 'Trailing plant with purple and silver-striped leaves; vibrant under good light.',
    idealConditions: 'Warm, bright locations; well-draining soil; high humidity preferred.',
    careTips: 'Water weekly (weekly). Prefers bright indirect light; prune regularly to encourage fullness. Common mistakes: letting soil dry too much, causing leaf drop.',
    isEndangered: false,
    isEdible: false,
    isPoisonous: false,
    uniqueFacts: 'Can root easily from cuttings even in water.',
    imageURL: '0'
  }
];

async function main() {
  console.log('Starting plant population...');
  
  let created = 0;
  let skipped = 0;
  
  for (const plant of plantData) {
    try {
      // Build tags array from additional data
      const tags: string[] = [];
      if (plant.isEndangered) tags.push('endangered');
      if (plant.isEdible) tags.push('edible');
      if (plant.isPoisonous) tags.push('poisonous');
      
      // Combine description with unique facts and ideal conditions
      const fullDescription = `${plant.description}\n\n${plant.uniqueFacts}`;
      const fullCareTips = `${plant.careTips}\n\nIdeal Conditions: ${plant.idealConditions}`;
      
      // Check if plant already exists (name is not unique, so use findFirst)
      const existing = await prisma.plant.findFirst({ where: { name: plant.commonName } });
      
      if (existing) {
        // Update existing plant
        await prisma.plant.update({
          where: { id: existing.id },
          data: {
            genus: plant.genus,
            species: plant.species,
            description: fullDescription,
            imageURL: plant.imageURL === '0' ? '/placeholder-plant.jpg' : plant.imageURL,
            cycle: plant.cycle,
            wateringFrequency: plant.wateringFrequency.toString(),
            nativeRegion: plant.nativeRegion,
            careTips: fullCareTips,
            tradeStatus: 'available',
            idealTemp: plant.idealTemp,
            sunlight: plant.sunlight.toString(),
            tags: tags,
          },
        });
        skipped++;
        console.log(`⊘ Updated: ${plant.commonName}`);
      } else {
        // Create new plant
        await prisma.plant.create({
          data: {
            name: plant.commonName,
            genus: plant.genus,
            species: plant.species,
            description: fullDescription,
            imageURL: plant.imageURL === '0' ? '/placeholder-plant.jpg' : plant.imageURL,
            cycle: plant.cycle,
            wateringFrequency: plant.wateringFrequency.toString(),
            nativeRegion: plant.nativeRegion,
            careTips: fullCareTips,
            tradeStatus: 'available',
            idealTemp: plant.idealTemp,
            sunlight: plant.sunlight.toString(),
            tags: tags,
          },
        });
        created++;
        console.log(`✓ Created: ${plant.commonName}`);
      }
    } catch (error: any) {
      console.error(`✗ Error processing ${plant.commonName}:`, error.message);
    }
  }
  
  console.log(`\n✅ Plant population complete!`);
  console.log(`   Created: ${created}`);
  console.log(`   Skipped: ${skipped}`);
  console.log(`   Total processed: ${plantData.length}`);
}

main()
  .catch((e) => {
    console.error('Fatal error:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });

